apiVersion: v1
kind: ConfigMap
metadata:
  name: hackforge-config
  namespace: hackforge
data:
  SPRING_PROFILES_ACTIVE: "prod"
  PORT: "8080"
  DB_URL: "jdbc:postgresql://postgres-service.hackforge.svc.cluster.local:5432/hackforge_prod"
  REDIS_HOST: "redis-service.hackforge.svc.cluster.local"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq-service.hackforge.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  CORS_ALLOWED_ORIGINS: "https://hackforge.io,https://app.hackforge.io"
